import database
from database import create_database, db_name

class Student():
    """Student class"""
    def __init__(self, id, firstName, middleName,
    lastName, gender, age, email, phone, nationality, degree):
        # id is to be generated by generateId method
        # so the parameter for id will be removed after the method is compeleted.
        self.id = id
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.gender = gender
        self.age = age
        self.email = email
        self.phone = phone
        self.nationality = nationality
        self.degree = degree

    def generateId(self):
        """Generates a unique id number for a student from a combination
        of the first name and a random number in the following format
        ID Format: (to be done later)"""


    def __str__(self):
        student = """
        Student Name: {} {} {}
        Gender: {}
        Age: {}
        Contact: {} / {} 
        Nationality: {}
        Degree: {}
        """.format(self.firstName, self.middleName, self.lastName,
                    self.gender,
                    self.age, 
                    self.email,self.phone, 
                    self.Nationality, self.degree)
        
        return student

# student = Student(1, "wubeshet", "anegagrie", "yimam", "male", 22, "wube@gmail.com",
# "+25198", "Ethiopia", "BSE")

def addStudent():
    id = input("Enter Id:")
    firstName = input("Enter first name: ")
    middleName = input("Enter middle name: ")
    lastName = input("Enter last name: ")
    gender = input("Enter gender: ")
    age = int(input("Enter age:"))
    email = input("Enter email: ")
    phone = input("Enter phone number: ")
    nationality = input("Enter nationality: ")
    degree = input("Enter degree: ")
    new_student = Student(id, firstName, middleName, lastName, gender, age, email, phone, nationality, degree)

    # excute database operation
    try:
        database.add_student(db_name, new_student)
        print("New student has been added successfully!")
        response = input("Do you want do Another operation? yes/no")
        if response.lower() == "yes":
            mainMenu()
        else:
            exit()
    except:
        print ("Can't add new student")
        

def updateStudent():
    pass
def getStudent():
    """get student by id"""
    pass
def deleteStudent():
    pass
def getAllStudents():
    """get all students"""
    pass

def choices():
    print("1. Add a new student")
    print("2. Update a student")
    print("3. Delete a student")
    print("4. Get a student by id")
    print("5. Get all students")
    print("6. Exit")
    choice = int(input("Enter your choice: "))
    return choice

def mainMenu():
    create_database(db_name)
    """menu items for user interation"""
    # print(s)
    print("============ STUDENT REGISTRATION =============")
    print("Let's know what you want to do")

    choice = choices()

    if choice == 1:
        addStudent()
    elif choice == 2:
        updateStudent()
    elif choice == 3:
        deleteStudent()
    elif choice == 4:
        getStudent()
    elif choice == 5:
        getAllStudents()
    elif choice == 6:
        exit()
    else:
        print("Invalid choice")
        response = input("Do you still want to continue? yes/no")
        if response.lower() == "yes":
            mainMenu()
        else:
            exit()

if __name__ == '__main__':
    mainMenu()